//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAgriculture
    {
        public int CustAgriId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> NoOfCow { get; set; }
        public Nullable<int> NoOfBuffelo { get; set; }
        public Nullable<decimal> AgricultureLand { get; set; }
        public Nullable<decimal> MilkProductionQty { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
