//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerAgricultures = new HashSet<CustomerAgriculture>();
            this.CustomerBanks = new HashSet<CustomerBank>();
            this.VLCMilkCollections = new HashSet<VLCMilkCollection>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Village { get; set; }
        public string Tehsil { get; set; }
        public string District { get; set; }
        public string AddressState { get; set; }
        public string PostalCode { get; set; }
        public string PIN { get; set; }
        public string Contact { get; set; }
        public string IdentificationNumber { get; set; }
        public string AlternateContact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Aniversary { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> VLCId { get; set; }
        public Nullable<System.DateTime> DateOfJoinVLC { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CustomerCode { get; set; }
        public string CustomerAddress { get; set; }
    
        public virtual VLC VLC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAgriculture> CustomerAgricultures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBank> CustomerBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VLCMilkCollection> VLCMilkCollections { get; set; }
    }
}
