//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCOrderDtl
    {
        public int DCOrderDtlId { get; set; }
        public int DCOrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> OrderTax { get; set; }
        public Nullable<decimal> OrderTotalPrice { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    
        public virtual DCOrder DCOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
