//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCPaymentDetail
    {
        public int DCPaymentId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> DCId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReceivedBy { get; set; }
        public string PaymentMode { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual DistributionCenter DistributionCenter { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
