//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockMilkCollection
    {
        public int DockMilkCollectionId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<int> TotalNoOfCan { get; set; }
        public Nullable<int> TotalRejectedCan { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> AverageFAT { get; set; }
        public Nullable<decimal> AverageSNF { get; set; }
        public Nullable<decimal> TotalRejectedQuantity { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
