//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockMilkCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DockMilkCollection()
        {
            this.DockMilkCollectionDtls = new HashSet<DockMilkCollectionDtl>();
            this.VLCPaymentDetails = new HashSet<VLCPaymentDetail>();
        }
    
        public int DockMilkCollectionId { get; set; }
        public int VLCId { get; set; }
        public System.DateTime CollectionDateTime { get; set; }
        public int ShiftId { get; set; }
        public Nullable<int> TotalCan { get; set; }
        public Nullable<int> TotalRejectedCan { get; set; }
        public decimal TotalQuantity { get; set; }
        public Nullable<decimal> RejectedQuantity { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public decimal TotalAmount { get; set; }
        public string BillNumber { get; set; }
        public string ReceiverName { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual VLC VLC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DockMilkCollectionDtl> DockMilkCollectionDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VLCPaymentDetail> VLCPaymentDetails { get; set; }
    }
}
