//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockMilkCollectionDtl
    {
        public int DockMilkCollectionDtlI { get; set; }
        public int DockMilkCollectionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> FAT { get; set; }
        public Nullable<decimal> CLR { get; set; }
        public Nullable<int> TotalCan { get; set; }
        public Nullable<int> TotalRejectedCan { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> RejectedQuantity { get; set; }
        public Nullable<decimal> RatePerUnit { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string RejectedReason { get; set; }
        public string Comments { get; set; }
    
        public virtual DockMilkCollection DockMilkCollection { get; set; }
    }
}
