//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockMilkCollectionDetail
    {
        public int DMCDId { get; set; }
        public Nullable<int> VLCId { get; set; }
        public Nullable<int> TotalNoOfCan { get; set; }
        public Nullable<int> TotalRejectedCan { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> FAT { get; set; }
        public Nullable<decimal> SNF { get; set; }
        public Nullable<decimal> RatePerUnit { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> MilkCollectionDate { get; set; }
        public Nullable<System.TimeSpan> MileCollectionTime { get; set; }
        public string CarrierName { get; set; }
        public string DockReceiverName { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual VLC VLC { get; set; }
    }
}
