//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLCExpenseDetail
    {
        public int VLCExpenseId { get; set; }
        public int VLCId { get; set; }
        public int ExpenseReason { get; set; }
        public Nullable<decimal> PaymentCrAmount { get; set; }
        public Nullable<decimal> PaymentDrAmount { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string ExpenseComments { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual VLC VLC { get; set; }
    }
}
